[package]
name = "SerialRustSimulator"
version = "0.1.0"
authors = ["Youssef Moawad <youssef_programming@icloud.com>"]

[dependencies]
num-complex = "0.2"
itertools = "0.7.8"
rand = "0.5.5"
lapacke = "0.2.0"
nalgebra = "0.16.6"
